//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 01:52:02 AM EEST 
//


package fi.jonix.huutonet.market.huuto.xml.ad;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.w3.org/2005/Atom}id"/>
 *         &lt;element ref="{http://www.w3.org/2005/Atom}title"/>
 *         &lt;element ref="{http://www.w3.org/2005/Atom}category"/>
 *         &lt;element ref="{http://www.w3.org/2005/Atom}author"/>
 *         &lt;element ref="{http://www.w3.org/2005/Atom}link" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://somt.sanoma.fi/somt}itemStatus"/>
 *         &lt;element ref="{http://www.w3.org/2005/Atom}content"/>
 *         &lt;element ref="{http://www.w3.org/2005/Atom}summary"/>
 *         &lt;element ref="{http://www.w3.org/2005/Atom}updated"/>
 *         &lt;element ref="{http://somt.sanoma.fi/somt}intention"/>
 *         &lt;element ref="{http://somt.sanoma.fi/somt}expirationTime"/>
 *         &lt;element ref="{http://somt.sanoma.fi/somt}condition"/>
 *         &lt;element ref="{http://somt.sanoma.fi/somt}location"/>
 *         &lt;element ref="{http://somt.sanoma.fi/somt}price"/>
 *         &lt;element ref="{http://somt.sanoma.fi/somt}quantity"/>
 *         &lt;element ref="{http://somt.sanoma.fi/somt}buyerRequirements"/>
 *         &lt;element ref="{http://somt.sanoma.fi/somt}deliveryMethods"/>
 *         &lt;element ref="{http://somt.sanoma.fi/somt}paymentMethods"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "title",
    "category",
    "author",
    "link",
    "itemStatus",
    "content",
    "summary",
    "updated",
    "intention",
    "expirationTime",
    "condition",
    "location",
    "price",
    "quantity",
    "buyerRequirements",
    "deliveryMethods",
    "paymentMethods"
})
@XmlRootElement(name = "entry", namespace = "http://www.w3.org/2005/Atom")
public class Entry {

    @XmlElement(namespace = "http://www.w3.org/2005/Atom", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String id;
    @XmlElement(namespace = "http://www.w3.org/2005/Atom", required = true)
    protected String title;
    @XmlElement(namespace = "http://www.w3.org/2005/Atom", required = true)
    protected Category category;
    @XmlElement(namespace = "http://www.w3.org/2005/Atom", required = true)
    protected Author author;
    @XmlElement(namespace = "http://www.w3.org/2005/Atom", required = true)
    protected List<Link> link;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String itemStatus;
    @XmlElement(namespace = "http://www.w3.org/2005/Atom", required = true)
    protected Content content;
    @XmlElement(namespace = "http://www.w3.org/2005/Atom", required = true)
    protected String summary;
    @XmlElement(namespace = "http://www.w3.org/2005/Atom", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updated;
    @XmlElement(required = true)
    protected Intention intention;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expirationTime;
    @XmlElement(required = true)
    protected Condition condition;
    @XmlElement(required = true)
    protected Location location;
    @XmlElement(required = true)
    protected Price price;
    @XmlElement(required = true)
    protected BigInteger quantity;
    @XmlElement(required = true)
    protected BuyerRequirements buyerRequirements;
    @XmlElement(required = true)
    protected DeliveryMethods deliveryMethods;
    @XmlElement(required = true)
    protected PaymentMethods paymentMethods;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategory(Category value) {
        this.category = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link Author }
     *     
     */
    public Author getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link Author }
     *     
     */
    public void setAuthor(Author value) {
        this.author = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the link property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Link }
     * 
     * 
     */
    public List<Link> getLink() {
        if (link == null) {
            link = new ArrayList<Link>();
        }
        return this.link;
    }

    /**
     * Gets the value of the itemStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemStatus() {
        return itemStatus;
    }

    /**
     * Sets the value of the itemStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemStatus(String value) {
        this.itemStatus = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link Content }
     *     
     */
    public Content getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link Content }
     *     
     */
    public void setContent(Content value) {
        this.content = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummary(String value) {
        this.summary = value;
    }

    /**
     * Gets the value of the updated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdated(XMLGregorianCalendar value) {
        this.updated = value;
    }

    /**
     * Gets the value of the intention property.
     * 
     * @return
     *     possible object is
     *     {@link Intention }
     *     
     */
    public Intention getIntention() {
        return intention;
    }

    /**
     * Sets the value of the intention property.
     * 
     * @param value
     *     allowed object is
     *     {@link Intention }
     *     
     */
    public void setIntention(Intention value) {
        this.intention = value;
    }

    /**
     * Gets the value of the expirationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpirationTime() {
        return expirationTime;
    }

    /**
     * Sets the value of the expirationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationTime(XMLGregorianCalendar value) {
        this.expirationTime = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link Condition }
     *     
     */
    public Condition getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Condition }
     *     
     */
    public void setCondition(Condition value) {
        this.condition = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link Price }
     *     
     */
    public Price getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link Price }
     *     
     */
    public void setPrice(Price value) {
        this.price = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuantity(BigInteger value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the buyerRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link BuyerRequirements }
     *     
     */
    public BuyerRequirements getBuyerRequirements() {
        return buyerRequirements;
    }

    /**
     * Sets the value of the buyerRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyerRequirements }
     *     
     */
    public void setBuyerRequirements(BuyerRequirements value) {
        this.buyerRequirements = value;
    }

    /**
     * Gets the value of the deliveryMethods property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryMethods }
     *     
     */
    public DeliveryMethods getDeliveryMethods() {
        return deliveryMethods;
    }

    /**
     * Sets the value of the deliveryMethods property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryMethods }
     *     
     */
    public void setDeliveryMethods(DeliveryMethods value) {
        this.deliveryMethods = value;
    }

    /**
     * Gets the value of the paymentMethods property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMethods }
     *     
     */
    public PaymentMethods getPaymentMethods() {
        return paymentMethods;
    }

    /**
     * Sets the value of the paymentMethods property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMethods }
     *     
     */
    public void setPaymentMethods(PaymentMethods value) {
        this.paymentMethods = value;
    }

}
