//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 01:52:02 AM EEST 
//


package fi.jonix.huutonet.market.huuto.xml.ad;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://somt.sanoma.fi/somt}currentPrice"/>
 *         &lt;element ref="{http://dev.huuto.net/somt}startingPrice"/>
 *         &lt;element ref="{http://dev.huuto.net/somt}minimumIncrease"/>
 *         &lt;element ref="{http://dev.huuto.net/somt}buyNowPrice"/>
 *         &lt;element ref="{http://somt.sanoma.fi/somt}taxPercentage"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "currentPrice",
    "startingPrice",
    "minimumIncrease",
    "buyNowPrice",
    "taxPercentage"
})
@XmlRootElement(name = "price")
public class Price {

    @XmlElement(required = true)
    protected CurrentPrice currentPrice;
    @XmlElement(namespace = "http://dev.huuto.net/somt", required = true)
    protected StartingPrice startingPrice;
    @XmlElement(namespace = "http://dev.huuto.net/somt", required = true)
    protected MinimumIncrease minimumIncrease;
    @XmlElement(namespace = "http://dev.huuto.net/somt", required = true)
    protected BuyNowPrice buyNowPrice;
    @XmlElement(required = true)
    protected BigDecimal taxPercentage;

    /**
     * Gets the value of the currentPrice property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentPrice }
     *     
     */
    public CurrentPrice getCurrentPrice() {
        return currentPrice;
    }

    /**
     * Sets the value of the currentPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentPrice }
     *     
     */
    public void setCurrentPrice(CurrentPrice value) {
        this.currentPrice = value;
    }

    /**
     * Gets the value of the startingPrice property.
     * 
     * @return
     *     possible object is
     *     {@link StartingPrice }
     *     
     */
    public StartingPrice getStartingPrice() {
        return startingPrice;
    }

    /**
     * Sets the value of the startingPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartingPrice }
     *     
     */
    public void setStartingPrice(StartingPrice value) {
        this.startingPrice = value;
    }

    /**
     * Gets the value of the minimumIncrease property.
     * 
     * @return
     *     possible object is
     *     {@link MinimumIncrease }
     *     
     */
    public MinimumIncrease getMinimumIncrease() {
        return minimumIncrease;
    }

    /**
     * Sets the value of the minimumIncrease property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinimumIncrease }
     *     
     */
    public void setMinimumIncrease(MinimumIncrease value) {
        this.minimumIncrease = value;
    }

    /**
     * Gets the value of the buyNowPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BuyNowPrice }
     *     
     */
    public BuyNowPrice getBuyNowPrice() {
        return buyNowPrice;
    }

    /**
     * Sets the value of the buyNowPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyNowPrice }
     *     
     */
    public void setBuyNowPrice(BuyNowPrice value) {
        this.buyNowPrice = value;
    }

    /**
     * Gets the value of the taxPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxPercentage() {
        return taxPercentage;
    }

    /**
     * Sets the value of the taxPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxPercentage(BigDecimal value) {
        this.taxPercentage = value;
    }

}
