//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.05 at 02:08:01 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://somt.sanoma.fi/somt", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fi.jonix.huutonet.market.huuto.xml.ad09beta;
